name: pygbag_build
on: [workflow_dispatch]

jobs:
  build-pygbag:
    name: Build multiple Pygbag games
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pygbag
        run: python -m pip install pygbag

      - name: Build game1
        run: |
          python -m pygbag --build games/testing_ball/main.py
          cp -r games/testing_ball/build/web/* build/testing_ball

      - name: Build game2
        run: |
          python -m pygbag --build games/testing_color/main.py
          cp -r games/testing_color/build/web/* build/testing_color

      - name: Deploy all games to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
